### ISSUE TITLE
Currency getValue is not locale-related

### ISSUE THREAD

**Issue by alexanderbob** [envoy93/CurrencyConverter#3]
getValue() method in com.shashov.currency.common.Currency class uses hard-coded Russian locale (replace all , with . and parse). It doesn't look good for me in case of XML source format change.

I propose to utilize java.util.Locale class to parse numeric string values with Locale passed somewhere as argument at XML source level. 

It should not depend on hardware/app setting because users can launch this app with not-Russian language/region/location settings.

**Comment by kshashov** [comment]
Thanks for the advice. Fixed
